# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'windows1.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QColor

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 400)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.toolBox = QtWidgets.QToolBox(self.centralwidget)
        self.toolBox.setObjectName("toolBox")
        self.page1 = QtWidgets.QWidget()
        self.page1.setGeometry(QtCore.QRect(0, 0, 115, 304))
        self.page1.setObjectName("page1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.page1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tool_Box_1 = QtWidgets.QLabel(self.page1)
        self.tool_Box_1.setObjectName("tool_Box_1")
        self.verticalLayout.addWidget(self.tool_Box_1)
        self.toolBox.addItem(self.page1, "")
        self.page2 = QtWidgets.QWidget()
        self.page2.setGeometry(QtCore.QRect(0, 0, 108, 30))
        self.page2.setObjectName("page2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.page2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tool_Box_2 = QtWidgets.QLabel(self.page2)
        self.tool_Box_2.setObjectName("tool_Box_2")
        self.verticalLayout_2.addWidget(self.tool_Box_2)
        self.toolBox.addItem(self.page2, "")
        self.page3 = QtWidgets.QWidget()
        self.page3.setGeometry(QtCore.QRect(0, 0, 108, 30))
        self.page3.setObjectName("page3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.page3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tool_Box_3 = QtWidgets.QLabel(self.page3)
        self.tool_Box_3.setObjectName("tool_Box_3")
        self.verticalLayout_3.addWidget(self.tool_Box_3)
        self.toolBox.addItem(self.page3, "")
        self.horizontalLayout.addWidget(self.toolBox)
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.contentPage1 = QtWidgets.QWidget()
        self.contentPage1.setObjectName("contentPage1")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.contentPage1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label = QtWidgets.QLabel(self.contentPage1)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.pushButton_downloader = PushButton(self.contentPage1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_downloader.sizePolicy().hasHeightForWidth())
        self.pushButton_downloader.setSizePolicy(sizePolicy)
        self.pushButton_downloader.setStyleSheet("QPushButton {\n"
"    background-color: rgb(170, 170, 255);\n"
"    border: 2px solid rgb(233, 233, 255);\n"
"    border-radius:10px;\n"
"    padding: 5px 15px;\n"
"    text-align: right;\n"
"}")
        self.pushButton_downloader.setObjectName("pushButton_downloader")
        self.verticalLayout_11.addWidget(self.pushButton_downloader)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_11.addItem(spacerItem)
        self.pushButton222 = PushButton(self.contentPage1)
        self.pushButton222.setObjectName("pushButton222")
        self.verticalLayout_11.addWidget(self.pushButton222)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.contentPage1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_5.sizePolicy().hasHeightForWidth())
        self.lineEdit_5.setSizePolicy(sizePolicy)
        self.lineEdit_5.setStyleSheet("\n"
"        QPushButton {\n"
"            background-color: #2a70f4;\n"
"            color: white; \n"
"            font-size: 13px;\n"
"            border-top-right-radius: 5px;\n"
"            border-bottom-right-radius: 5px;\n"
"        }\n"
"\n"
"        QPushButton:hover {\n"
"            background-color: #2361d0;\n"
"        }\n"
"        \n"
"        QPushButton:pressed {\n"
"            background-color: #2058bc;\n"
"        }\n"
" ")
        self.lineEdit_5.setReadOnly(True)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.verticalLayout_11.addWidget(self.lineEdit_5)
        self.horizontalLayout_4.addLayout(self.verticalLayout_11)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.contentPage1)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout_3.addWidget(self.lineEdit_3, 1, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.contentPage1)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_3.addWidget(self.lineEdit, 0, 0, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.contentPage1)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_3.addWidget(self.lineEdit_2, 3, 0, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.contentPage1)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout_3.addWidget(self.lineEdit_4, 2, 0, 1, 1)
        self.label_2 = AcrylicLabel(self.contentPage1,tintColor=QColor(105, 114, 168, 102))
        self.label_2 = AcrylicLabel(5, QColor(255, 255, 255, 3))
        self.label_2.setText("")
        self.label_2.setScaledContents(True)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 4, 0, 1, 1)
        self.horizontalLayout_3.addLayout(self.gridLayout_3)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4.setStretch(0, 1)
        self.horizontalLayout_4.setStretch(1, 4)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.verticalLayout_4.setStretch(1, 4)
        self.stackedWidget.addWidget(self.contentPage1)
        self.contentPage2 = QtWidgets.QWidget()
        self.contentPage2.setObjectName("contentPage2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.contentPage2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.page2_2 = QtWidgets.QLabel(self.contentPage2)
        self.page2_2.setObjectName("page2_2")
        self.verticalLayout_5.addWidget(self.page2_2)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.contentPage2)
        self.plainTextEdit.setStyleSheet(" QPlainTextEdit { \n"
"                background-color: #1E1E1E;\n"
"                color: #FFFFFF;\n"
"                font-family: Consolas;\n"
"                font-size: 10pt;}")
        self.plainTextEdit.setReadOnly(True)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.verticalLayout_5.addWidget(self.plainTextEdit)
        self.stackedWidget.addWidget(self.contentPage2)
        self.contentPage3 = QtWidgets.QWidget()
        self.contentPage3.setObjectName("contentPage3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.contentPage3)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.page3_3 = QtWidgets.QLabel(self.contentPage3)
        self.page3_3.setObjectName("page3_3")
        self.verticalLayout_6.addWidget(self.page3_3)
        self.stackedWidget.addWidget(self.contentPage3)
        self.horizontalLayout.addWidget(self.stackedWidget)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 4)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.toolBox.setCurrentIndex(0)
        self.stackedWidget.setCurrentIndex(0)
        self.toolBox.currentChanged['int'].connect(self.stackedWidget.setCurrentIndex) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "QToolBox多页切换示例"))
        self.tool_Box_1.setText(_translate("MainWindow", "这是页面1的内容"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page1), _translate("MainWindow", "主页"))
        self.tool_Box_2.setText(_translate("MainWindow", "这是页面2的内容"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page2), _translate("MainWindow", "日志"))
        self.tool_Box_3.setText(_translate("MainWindow", "这是页面3的内容"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page3), _translate("MainWindow", "其他工具"))
        self.label.setText(_translate("MainWindow", "novel_downloader"))
        self.pushButton_downloader.setText(_translate("MainWindow", "下载"))
        self.pushButton222.setText(_translate("MainWindow", "PushButton"))
        self.lineEdit_5.setPlaceholderText(_translate("MainWindow", "待填入内容"))
        self.lineEdit_3.setPlaceholderText(_translate("MainWindow", "目录页path：/kan/46118/"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "域名www.biquge.com/"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "章节内容selector"))
        self.lineEdit_4.setPlaceholderText(_translate("MainWindow", "章节目录页章节selector"))
        self.page2_2.setText(_translate("MainWindow", "内容区域 - 页面2"))
        self.plainTextEdit.setPlainText(_translate("MainWindow", "日志输出\n"
"\n"
""))
        self.page3_3.setText(_translate("MainWindow", "内容区域 - 页面3"))
from qfluentwidgets import PushButton
from qfluentwidgets.components.widgets.acrylic_label import AcrylicLabel
