# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'windows2.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1049, 657)
        MainWindow.setWindowOpacity(0.8)
        MainWindow.setStyleSheet("/* 主窗口 - 浅色主题基础 */\n"
"background-color: qlineargradient(spread:reflect, x1:0.471591, y1:0, x2:0.499545, y2:1, stop:0 rgba(255,45,45, 0), stop:1 rgba(193, 151, 255, 4));\n"
"QMainWindow, QWidget {\n"
"    font-family: -apple-system, BlinkMacSystemFont; /* 苹果系统字体 */\n"
"    color: #1D1D1F; /* 系统深灰色 */\n"
"}\n"
"\n"
"/* 背景框架 - 毛玻璃效果 */\n"
"QFrame#frame_MainBackground {\n"
"    background-color: rgba(242, 242, 247, 0.9); /* iOS系统背景色 */\n"
"    border-radius: 12px;\n"
"    border: 1px solid rgba(0,0,0,0.1);\n"
"}\n"
"\n"
"/* 通用按钮样式 - iOS 风格 */\n"
"PushButton, QPushButton {\n"
"    background-color: #007AFF; /* 系统蓝色 */\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    padding: 8px 16px;\n"
"    min-height: 28px;\n"
"    font-weight: 500;\n"
"}\n"
"\n"
"PushButton:hover, QPushButton:hover {\n"
"    background-color: #0063CC; /* 悬停加深 */\n"
"}\n"
"\n"
"PushButton:pressed, QPushButton:pressed {\n"
"    background-color: #004299; /* 按压效果 */\n"
"}\n"
"\n"
"/* 输入框 - 现代扁平风格 */\n"
"LineEdit, QLineEdit, QPlainTextEdit {\n"
"    background-color: rgba(255,255,255,0.9);\n"
"    border: 1px solid #C6C6C8;\n"
"    border-radius: 8px;\n"
"    padding: 6px 12px;\n"
"    selection-background-color: #007AFF;\n"
"}\n"
"\n"
"LineEdit:focus, QLineEdit:focus, QPlainTextEdit:focus {\n"
"    border-color: #007AFF;\n"
"    box-shadow: 0 0 0 2px rgba(0,122,255,0.2); /* iOS焦点效果 */\n"
"}\n"
"\n"
"/* 工具盒(QToolBox) - 侧边栏风格 */ \n"
"QToolBox::tab {\n"
"    background: rgba(242,242,247,0.8);\n"
"    border-radius: 8px;\n"
"    margin: 4px;\n"
"    padding: 12px;\n"
"}\n"
"\n"
"QToolBox::tab:selected {\n"
"    background: rgba(0,122,255,0.1);\n"
"    color: #007AFF;\n"
"}\n"
"\n"
"/* 堆叠窗口(QStackedWidget) - 卡片式布局 */\n"
"QStackedWidget QFrame {\n"
"    background: white;\n"
"    border-radius: 12px;\n"
"    border: 1px solid rgba(0,0,0,0.1);\n"
"    margin: 8px;\n"
"    padding: 16px;\n"
"}\n"
"\n"
"/* 标签文本 - 强调层次 */\n"
"QLabel {\n"
"    font-size: 13pt;\n"
"    color: #3A3A3C;\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"\n"
"/* 分隔间距 - iOS标准间距 */\n"
"QSpacerItem {\n"
"    width: 16px;  /* 水平间距 */\n"
"    height: 16px; /* 垂直间距 */\n"
"}\n"
"\n"
"/* 滚动条 - 简约风格 */\n"
"QScrollBar:vertical {\n"
"    width: 6px;\n"
"    background: transparent;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: #C6C6C8;\n"
"    border-radius: 3px;\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("Qcentralwidget=rgba(255, 255, 255, 0)")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.frame_MainBackground = QtWidgets.QFrame(self.centralwidget)
        self.frame_MainBackground.setStyleSheet("background-color: rgba(209, 209, 209, 0);")
        self.frame_MainBackground.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_MainBackground.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_MainBackground.setObjectName("frame_MainBackground")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.frame_MainBackground)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.label_title = QtWidgets.QLabel(self.frame_MainBackground)
        self.label_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_title.setObjectName("label_title")
        self.horizontalLayout_6.addWidget(self.label_title)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.horizontalLayout_6.setStretch(1, 1)
        self.verticalLayout_12.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.frame_7 = QtWidgets.QFrame(self.frame_MainBackground)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.toolBox_3 = QtWidgets.QToolBox(self.frame_7)
        self.toolBox_3.setStyleSheet("background-color: qlineargradient(spread:reflect, x1:0.471591, y1:0, x2:0.499545, y2:1, stop:0 rgba(231,231,231, 200), stop:1 rgba(231,231,231, 100));\n"
"border-radius: 10px;\n"
"")
        self.toolBox_3.setObjectName("toolBox_3")
        self.page_7 = QtWidgets.QWidget()
        self.page_7.setGeometry(QtCore.QRect(0, 0, 175, 513))
        self.page_7.setObjectName("page_7")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.page_7)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.pushButton_3 = QtWidgets.QPushButton(self.page_7)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_8.addWidget(self.pushButton_3)
        self.toolBox_3.addItem(self.page_7, "")
        self.page_8 = QtWidgets.QWidget()
        self.page_8.setGeometry(QtCore.QRect(0, 0, 100, 30))
        self.page_8.setObjectName("page_8")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.page_8)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.pushButton_4 = QtWidgets.QPushButton(self.page_8)
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_13.addWidget(self.pushButton_4)
        self.toolBox_3.addItem(self.page_8, "")
        self.horizontalLayout.addWidget(self.toolBox_3)
        self.horizontalLayout_11.addWidget(self.frame_7)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_11.addItem(spacerItem2)
        self.frame_8 = QtWidgets.QFrame(self.frame_MainBackground)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_8)
        self.stackedWidget.setObjectName("stackedWidget")
        self.contentPage1 = QtWidgets.QWidget()
        self.contentPage1.setObjectName("contentPage1")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.contentPage1)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.frame_9 = QtWidgets.QFrame(self.contentPage1)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.plainTextEdit_3 = QtWidgets.QPlainTextEdit(self.frame_9)
        self.plainTextEdit_3.setStyleSheet("background-color: rgb(170, 170, 255);\n"
"border-radius: 10px;")
        self.plainTextEdit_3.setObjectName("plainTextEdit_3")
        self.horizontalLayout_15.addWidget(self.plainTextEdit_3)
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.lineEdit_9 = LineEdit(self.frame_9)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.verticalLayout_18.addWidget(self.lineEdit_9)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lineEdit_12 = LineEdit(self.frame_9)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.gridLayout_3.addWidget(self.lineEdit_12, 0, 1, 1, 1)
        self.pushButton_downloader = PushButton(self.frame_9)
        self.pushButton_downloader.setObjectName("pushButton_downloader")
        self.gridLayout_3.addWidget(self.pushButton_downloader, 1, 0, 1, 1)
        self.lineEdit_11 = LineEdit(self.frame_9)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.gridLayout_3.addWidget(self.lineEdit_11, 1, 1, 1, 1)
        self.lineEdit_10 = LineEdit(self.frame_9)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.gridLayout_3.addWidget(self.lineEdit_10, 2, 1, 1, 1)
        self.verticalLayout_18.addLayout(self.gridLayout_3)
        self.verticalLayout_18.setStretch(0, 1)
        self.verticalLayout_18.setStretch(1, 1)
        self.verticalLayout_15.addLayout(self.verticalLayout_18)
        self.verticalLayout_15.setStretch(0, 1)
        self.horizontalLayout_15.addLayout(self.verticalLayout_15)
        self.horizontalLayout_16.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_7.addWidget(self.frame_9)
        self.stackedWidget.addWidget(self.contentPage1)
        self.contentPage2 = QtWidgets.QWidget()
        self.contentPage2.setObjectName("contentPage2")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.contentPage2)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.pushButton_6 = QtWidgets.QPushButton(self.contentPage2)
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_13.addWidget(self.pushButton_6)
        self.stackedWidget.addWidget(self.contentPage2)
        self.verticalLayout_17.addWidget(self.stackedWidget)
        self.horizontalLayout_9.addLayout(self.verticalLayout_17)
        self.horizontalLayout_11.addWidget(self.frame_8)
        self.horizontalLayout_11.setStretch(0, 1)
        self.horizontalLayout_11.setStretch(2, 4)
        self.verticalLayout_12.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12.addLayout(self.verticalLayout_12)
        self.verticalLayout_11.addWidget(self.frame_MainBackground)
        self.horizontalLayout_10.addLayout(self.verticalLayout_11)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.toolBox_3.setCurrentIndex(0)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_title.setText(_translate("MainWindow", "小说下载器"))
        self.pushButton_3.setText(_translate("MainWindow", "PushButton"))
        self.toolBox_3.setItemText(self.toolBox_3.indexOf(self.page_7), _translate("MainWindow", "Page 1"))
        self.pushButton_4.setText(_translate("MainWindow", "PushButton"))
        self.toolBox_3.setItemText(self.toolBox_3.indexOf(self.page_8), _translate("MainWindow", "Page 2"))
        self.pushButton_downloader.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_6.setText(_translate("MainWindow", "PushButton"))
from qfluentwidgets import LineEdit, PushButton
