# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'windows1.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(587, 586)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.toolBox = QtWidgets.QToolBox(self.centralwidget)
        self.toolBox.setObjectName("toolBox")
        self.page1 = QtWidgets.QWidget()
        self.page1.setGeometry(QtCore.QRect(0, 0, 108, 30))
        self.page1.setObjectName("page1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.page1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tool_Box_1 = QtWidgets.QLabel(self.page1)
        self.tool_Box_1.setObjectName("tool_Box_1")
        self.verticalLayout.addWidget(self.tool_Box_1)
        self.toolBox.addItem(self.page1, "")
        self.page2 = QtWidgets.QWidget()
        self.page2.setGeometry(QtCore.QRect(0, 0, 108, 488))
        self.page2.setObjectName("page2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.page2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tool_Box_2 = QtWidgets.QLabel(self.page2)
        self.tool_Box_2.setObjectName("tool_Box_2")
        self.verticalLayout_2.addWidget(self.tool_Box_2)
        self.toolBox.addItem(self.page2, "")
        self.page3 = QtWidgets.QWidget()
        self.page3.setGeometry(QtCore.QRect(0, 0, 108, 30))
        self.page3.setObjectName("page3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.page3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tool_Box_3 = QtWidgets.QLabel(self.page3)
        self.tool_Box_3.setObjectName("tool_Box_3")
        self.verticalLayout_3.addWidget(self.tool_Box_3)
        self.toolBox.addItem(self.page3, "")
        self.horizontalLayout.addWidget(self.toolBox)
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.contentPage1 = QtWidgets.QWidget()
        self.contentPage1.setObjectName("contentPage1")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.contentPage1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame = AcrylicFrame(self.contentPage1)
        self.frame.setStyleSheet("background-color: rgba(255, 255, 255, 30); /* 基础半透明白色 */\n"
"border: none;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.pushButton_downloader = PushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_downloader.sizePolicy().hasHeightForWidth())
        self.pushButton_downloader.setSizePolicy(sizePolicy)
        self.pushButton_downloader.setStyleSheet("QPushButton {\n"
"    background-color: rgb(170, 170, 255);\n"
"    border: 2px solid rgb(233, 233, 255);\n"
"    border-radius:10px;\n"
"    padding: 5px 15px;\n"
"    text-align: right;\n"
"    icon-align:left\n"
"}")
        self.pushButton_downloader.setObjectName("pushButton_downloader")
        self.verticalLayout_11.addWidget(self.pushButton_downloader)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_11.addItem(spacerItem)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_5.sizePolicy().hasHeightForWidth())
        self.lineEdit_5.setSizePolicy(sizePolicy)
        self.lineEdit_5.setStyleSheet("\n"
"        QPushButton {\n"
"            background-color: #2a70f4;\n"
"            color: white; \n"
"            font-size: 13px;\n"
"            border-top-right-radius: 5px;\n"
"            border-bottom-right-radius: 5px;\n"
"        }\n"
"\n"
"        QPushButton:hover {\n"
"            background-color: #2361d0;\n"
"        }\n"
"        \n"
"        QPushButton:pressed {\n"
"            background-color: #2058bc;\n"
"        }\n"
" ")
        self.lineEdit_5.setReadOnly(True)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.verticalLayout_11.addWidget(self.lineEdit_5)
        self.horizontalLayout_2.addLayout(self.verticalLayout_11)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lineEdit_4 = LineEdit(self.frame)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout_3.addWidget(self.lineEdit_4, 2, 0, 1, 1)
        self.lineEdit_2 = LineEdit(self.frame)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_3.addWidget(self.lineEdit_2, 4, 0, 1, 1)
        self.lineEdit_3 = LineEdit(self.frame)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout_3.addWidget(self.lineEdit_3, 1, 0, 1, 1)
        self.lineEdit = LineEdit(self.frame)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_3.addWidget(self.lineEdit, 0, 0, 1, 1)
        self.pushButton222 = PushButton(self.frame)
        self.pushButton222.setObjectName("pushButton222")
        self.gridLayout_3.addWidget(self.pushButton222, 3, 0, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout_3)
        self.horizontalLayout_2.setStretch(1, 1)
        self.verticalLayout_7.addLayout(self.horizontalLayout_2)
        self.verticalLayout_8.addLayout(self.verticalLayout_7)
        self.horizontalLayout_4.addWidget(self.frame)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.verticalLayout_4.setStretch(0, 1)
        self.stackedWidget.addWidget(self.contentPage1)
        self.contentPage2 = QtWidgets.QWidget()
        self.contentPage2.setObjectName("contentPage2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.contentPage2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.page2_2 = QtWidgets.QLabel(self.contentPage2)
        self.page2_2.setObjectName("page2_2")
        self.verticalLayout_5.addWidget(self.page2_2)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.contentPage2)
        self.plainTextEdit.setStyleSheet(" QPlainTextEdit { \n"
"                background-color: #1E1E1E;\n"
"                color: #FFFFFF;\n"
"                font-family: Consolas;\n"
"                font-size: 10pt;}")
        self.plainTextEdit.setReadOnly(True)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.verticalLayout_5.addWidget(self.plainTextEdit)
        self.stackedWidget.addWidget(self.contentPage2)
        self.contentPage3 = QtWidgets.QWidget()
        self.contentPage3.setObjectName("contentPage3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.contentPage3)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.page3_3 = QtWidgets.QLabel(self.contentPage3)
        self.page3_3.setObjectName("page3_3")
        self.verticalLayout_6.addWidget(self.page3_3)
        self.stackedWidget.addWidget(self.contentPage3)
        self.horizontalLayout.addWidget(self.stackedWidget)
        self.horizontalLayout.setStretch(1, 1)
        self.gridLayout_2.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.toolBox.setCurrentIndex(1)
        self.stackedWidget.setCurrentIndex(0)
        self.toolBox.currentChanged['int'].connect(self.stackedWidget.setCurrentIndex) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "QToolBox多页切换示例"))
        self.tool_Box_1.setText(_translate("MainWindow", "这是页面1的内容"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page1), _translate("MainWindow", "主页"))
        self.tool_Box_2.setText(_translate("MainWindow", "这是页面2的内容"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page2), _translate("MainWindow", "日志"))
        self.tool_Box_3.setText(_translate("MainWindow", "这是页面3的内容"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page3), _translate("MainWindow", "其他工具"))
        self.pushButton_downloader.setText(_translate("MainWindow", "下载"))
        self.lineEdit_5.setPlaceholderText(_translate("MainWindow", "待填入内容"))
        self.lineEdit_4.setPlaceholderText(_translate("MainWindow", "章节目录页章节selector"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "章节内容selector"))
        self.lineEdit_3.setPlaceholderText(_translate("MainWindow", "目录页path：/kan/46118/"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "域名www.biquge.com/"))
        self.pushButton222.setText(_translate("MainWindow", "PushButton"))
        self.page2_2.setText(_translate("MainWindow", "内容区域 - 页面2"))
        self.plainTextEdit.setPlainText(_translate("MainWindow", "日志输出\n"
"\n"
""))
        self.page3_3.setText(_translate("MainWindow", "内容区域 - 页面3"))
from AcrylicFrame import AcrylicFrame
from qfluentwidgets import LineEdit, PushButton
